<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNXgVxqa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNXgVxqa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNXgVxqa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNXgVxqa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNXgVxqa\App_KernelDevDebugContainer([
    'container.build_hash' => 'NXgVxqa',
    'container.build_id' => '8c42ae64',
    'container.build_time' => 1659861723,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNXgVxqa');
