<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8hKmz3D\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8hKmz3D/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8hKmz3D.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8hKmz3D\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8hKmz3D\App_KernelDevDebugContainer([
    'container.build_hash' => '8hKmz3D',
    'container.build_id' => '657b2083',
    'container.build_time' => 1657896995,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8hKmz3D');
