<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4IEzX9p\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4IEzX9p/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4IEzX9p.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4IEzX9p\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4IEzX9p\App_KernelDevDebugContainer([
    'container.build_hash' => '4IEzX9p',
    'container.build_id' => 'cf59a248',
    'container.build_time' => 1660238488,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4IEzX9p');
